spring.application.name=TracoCultural
server.port=8080

spring.datasource.url=${jdbc:sqlserver://TracoCulturalDB.mssql.somee.com;databaseName=TracoCulturalDB;integratedSecurity=false;encrypt=false;trustServerCertificate=true}
spring.datasource.username=${migskADM}
spring.datasource.password=${22102008@Mm}
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=none
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect 
 

jwt.secret=${TracoCulturalSecretKey2024MinimoDe32Caracteres}