spring.application.name=TracoCultural
server.port=8080
spring.datasource.url=jdbc:sqlserver://TracoCulturalDB.mssql.somee.com;databaseName=TracoCulturalDB;integratedSecurity=false;encrypt=false;trustServerCertificate=true
spring.datasource.username=migskADM
spring.datasource.password=22102008@Mm
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect

# JWT Configuration
jwt.secret=your_secret_key_here_minimum_256_bits_long_for_security_requirements_should_be_very_long

# Informacoes:

# integratedSecurity: (true) Indica que a conexao sera feita com as credenciais do Windows (false) Credencial do SQL SERVER
# encrypt: (true) Requer criptografia do Cliente (false) Nao requer criptografia do Cliente
# trustServerCertificate: (true) Instrui o aplicativo cliente a ignorar a validacao do certificado SSL/TSL do servidor